### ISSUE TITLE
Correctness of the gcd implementation of EuclideanDomain

### ISSUE THREAD

**Issue by dvberkel** [rjolly/scas#1]
At the moment the `EuclidianDomain` trait povides an implementation for greatest common divisor; [gcd](https://github.com/rjolly/scas/blob/a5d0e7f4e4847f95b338c23f21358d91f69c67d2/scas/src/scas/structure/commutative/EuclidianDomain.scala#L7).

This implementation seems incorrect to me. When applied to integers it returns wrong results. E.g. the greatest common divisor of 51 and 37 is `1` whereas the implementation would answer `51%37 = 14`.

To me a correct implementation would be

```scala
def gcd(x: T, y: T) = if (norm(x) < norm(y)) gcd(y, x) else if (y >< zero) x else gcd(y, x % y) 
```

**Comment by rjolly** [comment]
Good catch ! fixed.
